version: '3.9'

volumes:
  node_modules: {}

services:
  api:
    image: devmiguelangel/nsg-task-api
    build:
      context: .
      dockerfile: ./compose/app/Dockerfile
    container_name: nsg_task_api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    tty: true
